In [15]:
import tensorflow as tf


In [16]:
sess = tf.InteractiveSession()

Exception AssertionError: AssertionError("Nesting violated for default stack of <type 'weakref'> objects",) in <bound method InteractiveSession.__del__ of <tensorflow.python.client.session.InteractiveSession object at 0x7fa05e709b10>> ignored


In [23]:
x = tf.constant(2, dtype= tf.float32)
y = tf.placeholder(dtype= tf.float32, shape= [1])
inp = tf.placeholder(dtype= tf.bool, shape= [1])
#r = tf.cond(tf.less(x, y), f1, f2)
r = tf.cond(inp[0], lambda: x, lambda: y)
res = sess.run([r], feed_dict= {inp: [True]})
print (res)

# r is set to f1().
# Operations in f2 (e.g., tf.add) are not executed.

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_23' with dtype float and shape [1]
	 [[Node: Placeholder_23 = Placeholder[dtype=DT_FLOAT, shape=[1], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Caused by op u'Placeholder_23', defined at:
  File "/home/frederik/anaconda2/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/frederik/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frederik/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/frederik/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/home/frederik/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 442, in start
    ioloop.IOLoop.instance().start()
  File "/home/frederik/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 162, in start
    super(ZMQIOLoop, self).start()
  File "/home/frederik/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py", line 883, in start
    handler_func(fd_obj, events)
  File "/home/frederik/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/frederik/anaconda2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/frederik/anaconda2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/frederik/anaconda2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/frederik/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/frederik/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/frederik/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/frederik/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 391, in execute_request
    user_expressions, allow_stdin)
  File "/home/frederik/anaconda2/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 199, in do_execute
    shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/frederik/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2723, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/frederik/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2825, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/frederik/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-23-b33add7d3f31>", line 2, in <module>
    y = tf.placeholder(dtype= tf.float32, shape= [1])
  File "/home/frederik/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 895, in placeholder
    name=name)
  File "/home/frederik/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1238, in _placeholder
    name=name)
  File "/home/frederik/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 704, in apply_op
    op_def=op_def)
  File "/home/frederik/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2260, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/frederik/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1230, in __init__
    self._traceback = _extract_stack()


In [22]:
x = tf.constant(1, shape=(2,1), dtype= tf.float32 )
x_ = x*2
print(tf.shape(x_).eval())
print(tf.greater(x,x_).eval())
print
print(x.eval())
print(x_.eval())
a =tf.cond(tf.greater(x,x_),lambda: x, lambda: x_)
a.eval()

[2 1]
[[False]
 [False]]

[[ 1.]
 [ 1.]]
[[ 2.]
 [ 2.]]


ValueError: Shapes (2, 1) and () are not compatible

In [3]:
x = tf.placeholder(tf.float32, [None, 2], name='x-input')


In [4]:
import numpy as np
x_feed = np.ones((10,1))
x_feed = np.concatenate((x_feed, x_feed*2),axis = 1)
x_feed

array([[ 1.,  2.],
       [ 1.,  2.],
       [ 1.,  2.],
       [ 1.,  2.],
       [ 1.,  2.],
       [ 1.,  2.],
       [ 1.,  2.],
       [ 1.,  2.],
       [ 1.,  2.],
       [ 1.,  2.]])

In [5]:
x_ = x*2
x_.eval(feed_dict= {x: x_feed})

array([[ 2.,  4.],
       [ 2.,  4.],
       [ 2.,  4.],
       [ 2.,  4.],
       [ 2.,  4.],
       [ 2.,  4.],
       [ 2.,  4.],
       [ 2.,  4.],
       [ 2.,  4.],
       [ 2.,  4.]], dtype=float32)

In [6]:
x__ = tf.slice(input_= x_, begin= [0,0], size= [-1,1])
print(x__.eval(feed_dict= {x: x_feed}))


[[ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]]


In [7]:
x__shape = tf.shape_n(input=[x__])
x__shape[0].eval(feed_dict={x: x_feed})

array([10,  1], dtype=int32)

In [8]:
a = tf.constant([1 ,2])

In [9]:
c = tf.constant([1,10], shape=[1, 2], dtype=tf.float32)


In [10]:
c.eval()

array([[  1.,  10.]], dtype=float32)

In [11]:
c_ = tf.tile(c,[tf.shape(x_)[0],1])

In [12]:
tf.mul(x_,c_).eval(feed_dict={x: x_feed})

array([[  2.,  40.],
       [  2.,  40.],
       [  2.,  40.],
       [  2.,  40.],
       [  2.,  40.],
       [  2.,  40.],
       [  2.,  40.],
       [  2.,  40.],
       [  2.,  40.],
       [  2.,  40.]], dtype=float32)

In [27]:
x = tf.truncated_normal([10,2], mean=0, stddev=1.5, dtype=tf.float32)
print(x.eval())

[[-0.158813    1.77133346]
 [ 0.87237686 -1.09295547]
 [-0.10041773  1.09056079]
 [-2.79314137  2.22229767]
 [ 0.29225031 -1.41230857]
 [ 0.66840565  1.30554199]
 [-0.09482305 -0.25442618]
 [-1.83611119  1.96604156]
 [-1.39865112  0.42568493]
 [ 0.20962244 -0.18830238]]


In [28]:
mean, var = tf.nn.moments(x, axes= [0])
print(mean.eval())
print(var.eval())

[ 0.58605134 -0.03287976]
[ 0.8871752   1.40605807]


In [40]:
offset = tf.constant([0], shape= [10,2], dtype= tf.float32 )
scale = tf.constant([1], shape= [10,2], dtype= tf.float32 )

mean = tf.constant([0,0], shape= [1,2], dtype= tf.float32 )
print(mean.eval())
var = tf.constant([1,1], shape= [1,2], dtype= tf.float32 )
print(var.eval())
variance_epsilon = tf.constant([1e-6], shape= [1], dtype= tf.float32 )

bnx = tf.nn.batch_normalization(x, mean, var, None, None, variance_epsilon, name=None)


[[ 0.  0.]]
[[ 1.  1.]]


In [41]:
bnx_res, x_res = sess.run([bnx, x])
print(bnx_res)
print(x_res)

[[-0.62233335 -1.60913754]
 [ 1.08371496 -1.54664779]
 [ 0.71530092 -0.90577787]
 [-1.11423528  0.28348175]
 [ 1.192662    2.76610923]
 [-0.79604554 -0.81836849]
 [ 1.44703376 -0.6092152 ]
 [-1.30276906  1.6902281 ]
 [ 1.76405537  1.76658356]
 [ 1.52547836 -0.65387738]]
[[-0.62233365 -1.60913825]
 [ 1.08371544 -1.5466485 ]
 [ 0.71530128 -0.90577829]
 [-1.11423576  0.2834819 ]
 [ 1.1926626   2.76611066]
 [-0.7960459  -0.81836891]
 [ 1.44703448 -0.6092155 ]
 [-1.30276966  1.69022894]
 [ 1.76405621  1.7665844 ]
 [ 1.52547908 -0.65387768]]


In [4]:
x = tf.constant([1], shape= [1], dtype= tf.float32 )
x = x*2
y = tf.Variable(x)
y = x*2
x.eval()

array([ 2.], dtype=float32)

In [25]:
x = tf.constant([1], shape= [1], dtype= tf.float32 )
x_ = x*2
print(tf.greater(x,x_).eval())
print(x.eval())
print(x_.eval())
a =tf.cond(tf.greater(x,x_),lambda : x, lambda : x_)
a.eval()



[False]
[ 1.]
[ 2.]


ValueError: Shapes (1,) and () are not compatible

In [49]:
a = tf.constant(1)

In [64]:
b = tf.Variable(tf.constant(1))
tf.initialize_all_variables().run()
print(b.eval())

c= tf.Variable.assign_add(b, use_locking=False)



1


TypeError: assign_add() takes at least 2 arguments (2 given)