In [1]:
import tensorflow as tf


In [2]:
sess = tf.InteractiveSession()

In [3]:
x = tf.placeholder(tf.float32, [None, 2], name='x-input')


In [4]:
import numpy as np
x_feed = np.ones((10,1))
x_feed = np.concatenate((x_feed, x_feed*2),axis = 1)
x_feed

array([[ 1.,  2.],
       [ 1.,  2.],
       [ 1.,  2.],
       [ 1.,  2.],
       [ 1.,  2.],
       [ 1.,  2.],
       [ 1.,  2.],
       [ 1.,  2.],
       [ 1.,  2.],
       [ 1.,  2.]])

In [5]:
x_ = x*2
x_.eval(feed_dict= {x: x_feed})

array([[ 2.,  4.],
       [ 2.,  4.],
       [ 2.,  4.],
       [ 2.,  4.],
       [ 2.,  4.],
       [ 2.,  4.],
       [ 2.,  4.],
       [ 2.,  4.],
       [ 2.,  4.],
       [ 2.,  4.]], dtype=float32)

In [6]:
x__ = tf.slice(input_= x_, begin= [0,0], size= [-1,1])
print(x__.eval(feed_dict= {x: x_feed}))


[[ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]]


In [7]:
x__shape = tf.shape_n(input=[x__])
x__shape[0].eval(feed_dict={x: x_feed})

array([10,  1], dtype=int32)

In [8]:
a = tf.constant([1 ,2])

In [9]:
c = tf.constant([1,10], shape=[1, 2], dtype=tf.float32)


In [10]:
c.eval()

array([[  1.,  10.]], dtype=float32)

In [11]:
c_ = tf.tile(c,[tf.shape(x_)[0],1])

In [12]:
tf.mul(x_,c_).eval(feed_dict={x: x_feed})

array([[  2.,  40.],
       [  2.,  40.],
       [  2.,  40.],
       [  2.,  40.],
       [  2.,  40.],
       [  2.,  40.],
       [  2.,  40.],
       [  2.,  40.],
       [  2.,  40.],
       [  2.,  40.]], dtype=float32)